
on:
  push:
    branches:
    ["main"]

  pull_request:
    branches:
    ["main"] 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt 

    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Testing pizza planet app
      run: python3 -m pytest -v app/test
    - name: Coverage
      run: pytest --cov